---
- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Ensure kubeconfig is present
      stat:
        path: ./kubeconfig
      register: kubeconfig_stat

    - name: Fail if kubeconfig is not present
      fail:
        msg: "Kubeconfig not found"
      when: kubeconfig_stat.stat.exists == False

    - name: Deploy to Canary
      k8s:
        kubeconfig: ./kubeconfig
        state: present
        definition: ./train-schedule-kube-canary.yml

    - name: Deploy to Production
      k8s:
        kubeconfig: ./kubeconfig
        state: present
        definition: ./train-schedule-kube.yml
